### PR TITLE
Replace shortid to nanoid

### PR DESCRIPTION
**Pull request by ai**
What do you think of replacing `shortid` to [`nanoid`](https://github.com/ai/nanoid) (without big changes for users). Benefits:

1. `shortid` is not maintained anymore (and issue tracker has many important issues). I tried to took maintenance, but found that I can’t fix `shortid` with keeping API.
2. `shortid` has problem with random generator ([issue](https://github.com/dylang/shortid/issues/70)) and ID uniformity ([issue](https://github.com/dylang/shortid/issues/85)). `nanoid` use hardware random generator and has special uniformity tests ([docs](https://github.com/ai/nanoid#security)).
3. `shortid` has the problem with `-` symbol in the end of URL on some Android app ([issue](https://github.com/dylang/shortid/issues/96)). `nanoid` uses safe `~` instead of `-`.
4. `nanoid` is [10x times faster](https://github.com/ai/nanoid#benchmark) than `shortid`.

@bjrmatos what do you think?

### CODE REVIEW

**Comment by bjrmatos** [comment]
@ai sounds good to me, thanks for the PR. i will discuss this with @pofider and do some tests if this can have some impact for our users, but at the first glance this looks 100% compatible.

**Comment by pofider** [comment]
This sounds reasonable. Thank you for choosing our repo to send this PR

**Comment by ai** [comment]
Do I need to send PR to other jsreport tools or you can do it on your own?

**Comment by pofider** [comment]
Haha I was just joking with @bjrmatos on chat about asking you to do it. :)
We will do it step by step on our own. Thank you.

**Pull request merged**
